* Playground for Foundry

This is just to get to know [[https://book.getfoundry.sh/projects/dependencies][Foundry]]. This branch does not hold any actual implementation apart from
things which were automatically set up with ~forge init~.

** Set Up using Nix

This repo provides a [[./flake.nix]] file [fn:: The flake machinery used here is based on
https://github.com/shazow/foundry.nix.]. To get going you have to [[https://nixos.org/manual/nix/stable/installation/installing-binary.html][install nix]]. Furthermore, you have
to enable the [[https://nixos.wiki/wiki/Flakes][Flakes]] feature. On NixOS this is done by adding something along these lines to your
~configuration.nix~:
#+begin_src nix
  nix = {
    package = pkgs.nixFlakes;
    extraOptions = lib.optionalString (config.nix.package == pkgs.nixFlakes)
      "experimental-features = nix-command flakes";
  };
#+end_src
See https://nixos.wiki/wiki/Flakes for non-NixOS distributions.

You can now enter a development environment using ~nix develop~ and have all the necessary tools at
your hand. For a smoother developer experience consider using [[https://direnv.net/][direnv]].

** Repo Init Log

Briefly documenting the initialization routine:
+ run ~forge init --force --no-commit~;
+ ~forge build --no-auto-detect~ and ~forge test~ should now work.
